substitutions:
  _IMAGE_NAME: ice-test-manager
  _GCS_CACHE_BUCKET: general-mvn-bucket

steps:
  # load the cache from GCS if it exists
  - name: gcr.io/cloud-builders/gsutil
    dir: /root
    entrypoint: bash
    args:
      - -c
      - |
        (
          gsutil cp gs://${_GCS_CACHE_BUCKET}/${_IMAGE_NAME}-m2-cache.tar.gz /tmp/m2-cache.tar.gz &&
          tar -xzf /tmp/m2-cache.tar.gz
        ) || echo 'Cache not found'
    volumes:
      - name: m2
        path: /root/.m2/

  - name: "maven:3-jdk-8-slim"
    entrypoint: "mvn"
    args: ["-DskipTests", "clean", "install"]
    dir: "."
    volumes:
      - name: "m2"
        path: /root/.m2

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--tag=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BRANCH_NAME",
        "-f",
        ".gcp.config/Dockerfile",
        ".",
      ]
    dir: "."

  # cache the /root/.m2 folder and upload it to GCS bucket
  - name: gcr.io/cloud-builders/gsutil
    dir: /root
    entrypoint: bash
    args:
      - -c
      - |
        tar -czf /tmp/m2-cache.tar.gz .m2 &&
        gsutil cp /tmp/m2-cache.tar.gz gs://${_GCS_CACHE_BUCKET}/${_IMAGE_NAME}-m2-cache.tar.gz
    volumes:
      - name: m2
        path: /root/.m2/

  # create container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        ".gcp.config/Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/${_SVC}:$BRANCH_NAME",
        "-t",
        "gcr.io/$PROJECT_ID/${_SVC}:$SHORT_SHA",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    dir: "."
    id: docker-push-branch
    args: ["push", "gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BRANCH_NAME"]

  - name: "gcr.io/cloud-builders/docker"
    id: docker-push-sha
    args: ["push", "gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA"]

images: ["gcr.io/$PROJECT_ID/$_IMAGE_NAME"]
timeout: 900s
